name: CI/CD Pipeline (Windows Self-Hosted)

on:
  push:
    branches:
      - main

env:
  KAFKA_BOOTSTRAP_SERVERS: "mock"
  IMAGE_NAME: csv-ingestor
  IMAGE_TAG: latest
  K8S_NAMESPACE: kafka
  SKIP_KAFKA: "true"

jobs:
  test:
    runs-on: self-hosted

    steps:
      # 1️⃣ پاکسازی محتویات فولدر TEMP بدون حذف خود فولدر
      - name: Clean temp directory (Windows fix)
        shell: powershell
        run: |
          if (Test-Path $env:RUNNER_TEMP) {
              Get-ChildItem $env:RUNNER_TEMP -Recurse -Force |
                Remove-Item -Recurse -Force -ErrorAction SilentlyContinue
          }

      # 2️⃣ Checkout با clean=true برای جلوگیری از خطاهای EBUSY
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          clean: true

      # 3️⃣ نصب Python و dependencies
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        shell: powershell
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest

      # 4️⃣ اجرای تست‌ها
      - name: Run tests
        shell: powershell
        run: |
          $env:PYTHONPATH="$env:PYTHONPATH;$env:GITHUB_WORKSPACE"
          pytest --ignore=tests/integration/

  build-and-load:
    needs: test
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          clean: true

      - name: Build Docker image
        shell: powershell
        run: docker build -t $env:IMAGE_NAME:$env:IMAGE_TAG .

      - name: Load image into Kind
        shell: powershell
        run: kind load docker-image $env:IMAGE_NAME:$env:IMAGE_TAG --name kind

  deploy:
    needs: build-and-load
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          clean: true

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'v1.33.1'

      - name: Configure kubeconfig
        shell: powershell
        run: $env:KUBECONFIG="$HOME\.kube\config"

      - name: Deploy to Kubernetes
        shell: powershell
        run: |
          kubectl set image deployment/csv-ingestor csv-ingestor=$env:IMAGE_NAME:$env:IMAGE_TAG -n $env:K8S_NAMESPACE
          kubectl rollout status deployment/csv-ingestor -n $env:K8S_NAMESPACE
